"""empty message

Revision ID: 53114b1be5ae
Revises: 
Create Date: 2023-03-08 20:16:07.176516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53114b1be5ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradors',
    sa.Column('_od', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=True),
    sa.Column('ativo', sa.String(length=1), nullable=True),
    sa.Column('email_confirmado', sa.String(length=1), nullable=True),
    sa.Column('chave_email_confirmado', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sobrenome', sa.String(length=50), nullable=False),
    sa.Column('tel_ddi', sa.String(length=3), nullable=False),
    sa.Column('tel_ddd', sa.String(length=3), nullable=False),
    sa.Column('tel_numero', sa.String(length=10), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('_od'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('curadoria', sa.String(length=1), nullable=False),
    sa.Column('curadoria_at', sa.DateTime(), nullable=True),
    sa.Column('curadoria_id', sa.String(length=36), nullable=True),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=13), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=45), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=45), nullable=True),
    sa.Column('tel_ddi', sa.String(length=3), nullable=True),
    sa.Column('tel_ddd', sa.String(length=3), nullable=True),
    sa.Column('tel_numero', sa.String(length=11), nullable=True),
    sa.Column('end_cep', sa.String(length=8), nullable=True),
    sa.Column('end_pais', sa.String(length=20), nullable=False),
    sa.Column('end_estado', sa.String(length=2), nullable=True),
    sa.Column('end_cidade', sa.String(length=30), nullable=True),
    sa.Column('end_bairro', sa.String(length=20), nullable=True),
    sa.Column('end_tipo_logradouro', sa.String(length=10), nullable=True),
    sa.Column('end_logradouro', sa.String(length=30), nullable=True),
    sa.Column('end_numero', sa.String(length=10), nullable=True),
    sa.Column('end_complemento', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('planos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('preco_plano', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('pagseguro', sa.String(length=36), nullable=False),
    sa.Column('ativo', sa.String(length=1), nullable=True),
    sa.Column('inativo_at', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(length=500), nullable=True),
    sa.Column('inativo_administrador_id', sa.String(length=36), nullable=True),
    sa.Column('administrador_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradors._od'], ),
    sa.ForeignKeyConstraint(['inativo_administrador_id'], ['administradors._od'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pagseguro')
    )
    op.create_table('testes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('especie', sa.String(length=20), nullable=False),
    sa.Column('material_amostra', sa.String(length=45), nullable=False),
    sa.Column('peso_link', sa.String(length=255), nullable=False),
    sa.Column('responsavel_tecnico', sa.String(length=50), nullable=True),
    sa.Column('observacao_interna', sa.String(length=500), nullable=True),
    sa.Column('observacao_exame', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('administrador_id', sa.String(length=36), nullable=True),
    sa.Column('peso_administrador_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradors._od'], ),
    sa.ForeignKeyConstraint(['peso_administrador_id'], ['administradors._od'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('_od', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=True),
    sa.Column('ativo', sa.String(length=1), nullable=True),
    sa.Column('email_confirmado', sa.String(length=1), nullable=True),
    sa.Column('chave_email_confirmado', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sobrenome', sa.String(length=50), nullable=False),
    sa.Column('tel_ddi', sa.String(length=3), nullable=False),
    sa.Column('tel_ddd', sa.String(length=3), nullable=False),
    sa.Column('tel_numero', sa.String(length=10), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('_od'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('testes')
    op.drop_table('planos')
    op.drop_table('clientes')
    op.drop_table('administradors')
    # ### end Alembic commands ###
