"""empty message

Revision ID: dde23a19fde0
Revises: 53114b1be5ae
Create Date: 2023-03-09 08:58:45.951530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dde23a19fde0'
down_revision = '53114b1be5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cliente_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cliente_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
